ONX.CRM/Controllers/CoursesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ONX.CRM.BLL.Interfaces;
using ONX.CRM.Filters;
using ONX.CRM.ViewModel;

namespace ONX.CRM.Controllers
{
    [TypeFilter(typeof(LocalExceptionFilter))]
    public class CoursesController : BaseController
    {
        private readonly ISpecializationService _specializationService;
        private readonly ICourseService _courseService;
        private readonly IMapper _mapper;
        private readonly ILogger<CoursesController> _logger;
        public CoursesController(ICourseService courseService,
            ISpecializationService specializationService, 
            IMapper mapper, ILogger<CoursesController> logger)
        {
            _specializationService = specializationService;
            _courseService = courseService;
            _mapper = mapper;
            _logger = logger;
        }
        public async Task<IActionResult> Index(int id)
        {
            var specializationTitle = await _specializationService.GetEntityByIdAsync(id);
            ViewBag.SpecializationTitle = specializationTitle.Title;
            var courses = await _courseService.GetAllAsync();
            return View(_mapper
                .Map<IEnumerable<CourseViewModel>>(courses.Where(_ => _.SpecializationId == id)).ToList());
        }
    }
}

ONX.CRM/Controllers/SpecializationsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ONX.CRM.BLL.Interfaces;
using ONX.CRM.Filters;
using ONX.CRM.ViewModel;

namespace ONX.CRM.Controllers
{
    [TypeFilter(typeof(LocalExceptionFilter))]
    public class SpecializationsController : BaseController
    {
        private readonly ISpecializationService _specializationService;
        private readonly IMapper _mapper;
        public SpecializationsController(ISpecializationService specializationService, IMapper mapper)
        {
            _specializationService = specializationService;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            return View(_mapper.
                Map<IEnumerable<SpecializationViewModel>>(await _specializationService.GetAllAsync()).ToList());
        }
    }
}

ONX.CRM/Views/Courses/Index.cshtml
@using ONX.CRM.ViewModel
@{
    string specializationTitle = ViewBag.SpecializationTitle;
}

@model List<CourseViewModel>

<div class="page-wrapper">
    <div class="page-content">
        <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
            <div class="breadcrumb-title pe-3">ONX-Academy</div>
            <div class="ps-3">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb mb-0 p-0">
                        <li class="breadcrumb-item">
                            <a asp-controller="Home" asp-action="Index"><i class="bx bx-home-alt"></i></a>
                        </li>
                        <li class="breadcrumb-item" aria-current="page">

                            <a asp-controller="Specializations" asp-action="Index">Specializations</a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">
                            @specializationTitle.ToUpper()
                        </li>
                    </ol>
                </nav>
            </div>
        </div>
        <div class="container">
            <h1 class="display-4">@specializationTitle.ToUpper()<br></h1>
            <hr />
            <div class="card-group shadow">
                @foreach (var course in Model)
                {
                    <div class="card border-end shadow-none">
                        <div class="card-body">
                            <h4 class="card-title">@course.Title<br></h4>
                            <p class="card-text">@course.Description</p>
                            @if (@course.NecessaryPreKnowledge != null)
                            {
                                <p>Necessary pre-knowledge:&nbsp;<br>@course.NecessaryPreKnowledge<br></p>
                            }
                            <p>Cost : @course.Cost BYN<br></p>
                            <a asp-controller="Requests" asp-action="EditFromQuery"
                               asp-route-id="@course.Id" class="btn btn-outline-primary radius-15">
                                Enroll in a course
                            </a>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>