ONX.CRM/Controllers/CoursesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ONX.CRM.BLL.Interfaces;
using ONX.CRM.Filters;
using ONX.CRM.ViewModel;

namespace ONX.CRM.Controllers
{
    [TypeFilter(typeof(LocalExceptionFilter))]
    public class CoursesController : BaseController
    {
        private readonly ISpecializationService _specializationService;
        private readonly ICourseService _courseService;
        private readonly IMapper _mapper;
        private readonly ILogger<CoursesController> _logger;
        public CoursesController(ICourseService courseService,
            ISpecializationService specializationService, 
            IMapper mapper, ILogger<CoursesController> logger)
        {
            _specializationService = specializationService;
            _courseService = courseService;
            _mapper = mapper;
            _logger = logger;
        }
        public async Task<IActionResult> Index(int id)
        {
            var specializationTitle = await _specializationService.GetEntityByIdAsync(id);
            ViewBag.SpecializationTitle = specializationTitle.Title;
            var courses = await _courseService.GetAllAsync();
            return View(_mapper
                .Map<IEnumerable<CourseViewModel>>(courses.Where(_ => _.SpecializationId == id)).ToList());
        }
    }
}

ONX.CRM/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ONX.CRM.BLL.Interfaces;
using ONX.CRM.DAL.Models;
using ONX.CRM.Extensions;
using ONX.CRM.Filters;
using ONX.CRM.ViewModel;
using ONX.CRM.ViewModel.PageInfo;
using ONX.CRM.ViewModel.Search;

namespace ONX.CRM.Controllers
{
    [TypeFilter(typeof(LocalExceptionFilter))]
    public class RequestsController : BaseController
    {
        private readonly IMapper _mapper;
        private readonly ILogger<RequestsController> _logger;
        private readonly IStudentService _studentService;
        private readonly ICourseService _courseService;
        private readonly IStudentRequestService _studentRequestService;
        private readonly IGroupService _groupService;
        private readonly ISpecializationService _specializationService;
        private readonly PageInfoViewModel _pageInfo;

        public RequestsController(IStudentRequestService studentRequestsService,
            IStudentService studentService, ICourseService courseService,
            IMapper mapper, ILogger<RequestsController> logger, IGroupService groupService,
            ISpecializationService specializationService, PageInfoViewModel pageInfo)
        {
            _pageInfo = pageInfo;
            _specializationService = specializationService;
            _groupService = groupService;
            _mapper = mapper;
            _logger = logger;
            _courseService = courseService;
            _studentService = studentService;
            _studentRequestService = studentRequestsService;
        }
        [HttpGet]
        //[Authorize(Roles = "manager")]
        public async Task<IActionResult> Index(int courseId, int pageSize, int pageNumber)
        {

            PageInfoViewModel pageInfo;
            int skip;
            int take;
            //Получаем список курсов по которым есть заявки
            ViewBag.CoursesList = await _studentRequestService.GetActiveCoursesIdTitle();

            if (courseId != 0)
            {
                ViewBag.AllRequestsShow = false;

                pageInfo = _pageInfo.CheckingPageInfo(pageSize, pageNumber,
                    await _studentRequestService.GetNumberOfRequestsByCourseId(courseId));
                skip = (pageInfo.PageNumber - 1) * pageInfo.PageSize;
                take = pageInfo.PageSize;
                var requestsList = _mapper.Map<IEnumerable<StudentRequestViewModel>>(await _studentRequestService
                    .GetRequestsByCourseId(courseId, skip, take));

                //Если у заявок отфильтрованых по фильтру есть группа то разрешаем добавить студента в эту группу 
                var groups = _mapper.Map<IEnumerable<GroupViewModel>>(await _groupService.GetAllAsync())
                    .Where(g => g.CourseId == courseId);
                if (groups.Count() != 0)
                {
                    ViewBag.GroupExists = true;
                    ViewBag.CheckingAllowed = true;
                    ViewBag.Groups = groups;
                    return View(new RequestsListViewModel
                    {
                        Search = new SearchRequestViewModel { CourseId = courseId },
                        PageInfo = pageInfo,
                        RequestsList = requestsList.ToList()
                    });
                }
                //Иначе предложим создать новую группу
                ViewBag.GroupExists = false;
                ViewBag.CheckingAllowed = false;
                return View(new RequestsListViewModel
                {
                    Search = new SearchRequestViewModel { CourseId = courseId },
                    PageInfo = pageInfo,
                    RequestsList = requestsList.ToList()
                });
            }
            //Запуск Index без фильтрации по курсам
            pageInfo = _pageInfo.CheckingPageInfo(pageSize, pageNumber, await _studentRequestService.GetNumberOfRequests());
            skip = (pageInfo.PageNumber - 1) * pageInfo.PageSize;
            take = pageInfo.PageSize;
            var requests = _mapper.Map<IEnumerable<StudentRequestViewModel>>(await _studentRequestService.GetRequestsWithSkipAndTakeAsync(skip, take));

            ViewBag.AllRequestsShow = true;
            ViewBag.CheckingAllowed = false;

            return View(new RequestsListViewModel()
            {
                Search = new SearchRequestViewModel(),
                PageInfo = pageInfo,
                RequestsList = requests.ToList()
            });
        }
        [HttpPost]
        public async Task<IActionResult> Index(RequestsListViewModel model)
        {
            if (model.RequestsList != null)
            {
                var requests = _mapper.Map<IEnumerable<StudentRequest>>(model.RequestsList.Where(r => r.Selected));
                foreach (var request in requests)
                {
                    if (await _studentService.CheckIfManagerExists(request.Email))
                    {
                        ModelState.AddModelError("Email", "A user with this address is already registered.");
                        return View(model);
                    }
                }
                _studentRequestService.AssignRequestToGroups(requests, model.GroupId);
                //Если заявку была одна и мы добавили ее в группу то преадресовываем на все заявки
                if (model.RequestsList.Count == 1)
                {
                    return RedirectToAction("Index", "Requests");
                }
            }
            if (model.PageInfo == null)
            {
                return RedirectToAction("Index", "Requests", new
                {
                    courseId = model.Search.CourseId
                }, null);
            }
            return RedirectToAction("Index", "Requests", new
            {
                pageSize = model.PageInfo.PageSize,
                pageNumber = model.PageInfo.PageNumber,
                courseId = model.Search.CourseId,
            }, null);
        }
        [HttpGet]
        //[Authorize(Roles = "manager")]
        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.Courses = _mapper.Map<IEnumerable<CourseViewModel>>(await _courseService.GetAllAsync());
            ViewBag.Students = _mapper.Map<IEnumerable<StudentViewModel>>(await _studentService.GetAllAsync());
            return View(id.HasValue
                ? _mapper.Map<StudentRequestViewModel>(await _studentRequestService.GetEntityByIdAsync(id.Value))
                : new StudentRequestViewModel() { Created = null });
        }
        [HttpPost]
        public async Task<IActionResult> Edit(StudentRequestViewModel studentRequest)
        {
            ViewBag.CoursesSelected = false;
            ViewBag.Courses = _mapper.Map<IEnumerable<CourseViewModel>>(await _courseService.GetAllAsync());
            ViewBag.Students = _mapper.Map<IEnumerable<StudentViewModel>>(await _studentService.GetAllAsync());
            var course = await _courseService.GetEntityByIdAsync(studentRequest.CourseId);
            ViewBag.CourseName = course.Title;
            if (studentRequest.Created == null)
            {
                studentRequest.Created = DateTime.Now;
            }
            if (!ModelState.IsValid)
                if (studentRequest.Id == 0)
                    return View(new StudentRequestViewModel());
                else
                    return View(studentRequest);
            if (studentRequest.Id != 0)
            {
                if (await _studentService.CheckIfManagerExists(studentRequest.Email))
                {
                    ModelState.AddModelError("Email", "A user with this address is already registered.");
                    return View(studentRequest);
                }
                _studentRequestService.Update(_mapper.Map<StudentRequest>(studentRequest));
            }
            else
            {
                if (await _studentService.CheckIfManagerExists(studentRequest.Email))
                {
                    ModelState.AddModelError("Email", "A user with this address is already registered.");
                    return View(studentRequest);
                }
                _studentRequestService.Create(_mapper.Map<StudentRequest>(studentRequest));
            }

            if (User.IsInRole("manager") || User.IsInRole("admin"))
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index", "Specializations");
        }
        [HttpGet]
        public async Task<IActionResult> EditFromQuery(int id)
        {
            var course = await _courseService.GetEntityByIdAsync(id);
            ViewBag.CourseName = course.Title;
            ViewBag.SpecializationId = course.SpecializationId;
            var specialization = await _specializationService.GetEntityByIdAsync(course.SpecializationId);
            ViewBag.SpecializationTitle = specialization.Title;
           
            ViewBag.Courses = _mapper.Map<IEnumerable<CourseViewModel>>(await _courseService.GetAllAsync());
            ViewBag.Students = _mapper.Map<IEnumerable<StudentViewModel>>(await _studentService.GetAllAsync());
            return View("Edit", new StudentRequestViewModel() { Created = null, CourseId = id });
        }
        [HttpPost]
        //[Authorize(Roles = "manager")]
        public IActionResult Delete(int id)
        {
            _studentRequestService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

ONX.CRM/Controllers/SpecializationsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ONX.CRM.BLL.Interfaces;
using ONX.CRM.Filters;
using ONX.CRM.ViewModel;

namespace ONX.CRM.Controllers
{
    [TypeFilter(typeof(LocalExceptionFilter))]
    public class SpecializationsController : BaseController
    {
        private readonly ISpecializationService _specializationService;
        private readonly IMapper _mapper;
        public SpecializationsController(ISpecializationService specializationService, IMapper mapper)
        {
            _specializationService = specializationService;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            return View(_mapper.
                Map<IEnumerable<SpecializationViewModel>>(await _specializationService.GetAllAsync()).ToList());
        }
    }
}

ONX.CRM/Views/Requests/Edit.cshtml
@{
    var specializationTitle = ViewBag.SpecializationTitle;
    var courseName = ViewBag.CourseName;
    var managerCreateRequest = Model.Id == 0 & Model.CourseId == 0;
    var managerEditRequest = Model.Id != 0 & Model.CourseId != 0;
    var managerEditRequestSecondVariant = Model.Id != 0 & Model.CourseId == 0;
    var studentCreateRequest = Model.Id == 0 & Model.CourseId != 0;
    var headerText = string.Empty;
    var studentTypeList = new Dictionary<int, string>
    {
        [1] = "Online",
        [2] = "Offline",
        [3] = "Mix"
    };
    @if (managerCreateRequest)
    {
        headerText = "Create request";
    }
    else if (studentCreateRequest)
    {
        headerText = $"Your application for the course {courseName.ToString()}";
    }
    else if (managerEditRequest)
    {
        headerText = "Edit request";
    }

}
@model StudentRequestViewModel

<div class="page-wrapper">
    <div class="page-content">
        <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
            @if (!User.Identity.IsAuthenticated)
            {
                <div class="breadcrumb-title pe-3">ONX-Academy</div>
            }
            @if (User.Identity.IsAuthenticated && User.IsInRole("manager"))
            {
                <div class="breadcrumb-title pe-3">ONX.CRM</div>
            }
            <div class="ps-3">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb mb-0 p-0">
                        <li class="breadcrumb-item">
                            <a asp-controller="Home" asp-action="Index"><i class="bx bx-home-alt"></i></a>
                        </li>
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="breadcrumb-item" aria-current="page">
                                <a asp-controller="Specializations" asp-action="Index">Specializations</a>
                            </li>
                            <li class="breadcrumb-item" aria-current="page">
                                <a asp-controller="Courses" asp-route-id="@ViewBag.SpecializationId"
                                   asp-action="Index">@specializationTitle</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">
                                Create
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated && User.IsInRole("manager"))
                        {
                            @if (Model.Id == 0)
                            {
                                <li class="breadcrumb-item active" aria-current="page">Create</li>
                            }
                            else
                            {
                                <li class="breadcrumb-item active" aria-current="page">Edit</li>
                            }
                        }
                    </ol>
                </nav>
            </div>
        </div>
        <div class="card">
            <div class="row g-0">
                <div class="col-lg-5 border-end">
                    <div class="card-body">
                        <form asp-controller="Requests" asp-action="Edit" method="post">
                            <h2 class="text-center m-0">Request</h2>
                            <div class="card-body">
                                <div>
                                    <input type="hidden" asp-for="Id" value="@Model.Id" />
                                </div>
                                <div class="row mb-3">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">First Name</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        <input type="text" class="form-control" asp-for="FirstName" />
                                        <span class="alert-danger" asp-validation-for="FirstName"></span>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Last Name</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        <input type="text" class="form-control" asp-for="LastName" />
                                        <span class="alert-danger" asp-validation-for="LastName"></span>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Email Address</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        <input type="text" class="form-control" asp-for="Email" />
                                        <span class="alert-danger" asp-validation-for="Email"></span>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Phone</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        <input type="text" placeholder="+375(XX)XXX-XX-XX" class="form-control" asp-for="Phone" />
                                        <span class="alert-danger" asp-validation-for="Phone"></span>
                                    </div>
                                </div>
                                @if (managerCreateRequest || managerEditRequest || managerEditRequestSecondVariant)
                                {
                                    <div class="row mb-3">
                                        <div class="col-sm-3">
                                            <h6 class="mb-0">Course</h6>
                                        </div>
                                        <div class="col-sm-9 text-secondary">
                                            <select asp-for="CourseId" class="form-select" aria-label="Default select example">
                                                @if (managerCreateRequest)
                                                {
                                                    <option selected value="">Choose...</option>

                                                }
                                                @foreach (CourseViewModel course in ViewBag.Courses)
                                                {
                                                    <option value="@course.Id">@course.Title</option>
                                                }
                                            </select>
                                        </div>
                                    </div>
                                }
                                @Html.HiddenFor(m => m.CourseId)
                                <div class="row mb-3">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Type of Training</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        <select asp-for="Type" class="form-select" aria-label="Default select example">
                                            <option selected value="">Choose...</option>
                                            @foreach (var type in studentTypeList)
                                            {
                                                <option value="@type.Key">@type.Value</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Comments</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        <textarea class="form-control" asp-for="Comments" rows="3"></textarea>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-3"></div>
                                    <div class="col-sm-9 text-secondary">

                                        <button type="submit" class="btn btn-outline-primary px-4">Save</button>
                                        @if (studentCreateRequest)
                                        {
                                            <a type="button" class="btn btn-outline-danger px-4" asp-controller="Courses"
                                               asp-route-id="@ViewBag.SpecializationId" asp-action="Index">Cancel</a>
                                        }
                                        else
                                        {
                                            <a type="button" class="btn btn-outline-danger px-4" asp-controller="Requests"
                                               asp-action="Index">Cancel</a>
                                        }
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-7">
                    <img src="~/assets/images/login-images/elektronnaia-pochta.jpg" class="card-img login-img h-100" alt="...">
                </div>
            </div>
        </div>

    </div>
</div>
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial.cshtml")
}