ONX.CRM/Controllers/ManagersController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using ONX.CRM.BLL.Interfaces;
using ONX.CRM.DAL.Models;
using ONX.CRM.Filters;
using ONX.CRM.ViewModel;

namespace ONX.CRM.Controllers
{
    [TypeFilter(typeof(LocalExceptionFilter))]
    public class ManagersController : BaseController
    {
        private readonly IManagerService _managerService;
        private readonly IMapper _mapper;
        private readonly IUserService _userService;
        private readonly INotificationService _notificationService;
        public ManagersController(IManagerService managerService, IMapper mapper,
            IUserService userService, INotificationService notificationService)
        {
            _mapper = mapper;
            _managerService = managerService;
            _userService = userService;
            _notificationService = notificationService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {

            ViewBag.Managers = _mapper.Map<IEnumerable<ManagerViewModel>>(await _managerService.GetAllAsync());
            return View();

        }
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            return View(id.HasValue
                ? _mapper.Map<ManagerViewModel>(await _managerService.GetEntityByIdAsync(id.Value))
                : new ManagerViewModel());
        }
        [HttpPost]
        public async Task<IActionResult> Edit(ManagerViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            if (model.Id != 0)
            {
                await _userService.Update(model.UserId, model.Email, model.FirstName, model.LastName);
                _managerService.Update(_mapper.Map<Manager>(model));
            }
            else
            {
                if (await _managerService.CheckIfManagerExists(model.Email))
                {
                    ModelState.AddModelError("Email", "A user with this address is already registered.");
                    return View(model);
                }
                User user = new User
                {
                    Email = model.Email,
                    UserName = model.Email,
                    LastName = model.LastName,
                    FirstName = model.FirstName
                };
                await _userService.CreateAsync(user, "manager");
                model.UserId = user.Id;
                _managerService.Create(_mapper.Map<Manager>(model));
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(int id)
        {
            var manager = await _managerService.GetEntityByIdAsync(id);
            await _userService.Delete(manager.UserId);

            _managerService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

ONX.CRM/Views/Managers/Edit.cshtml
@{

}
@model ManagerViewModel

<div class="page-wrapper">
    <div class="page-content">
        <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
            <div class="breadcrumb-title pe-3">ONX.CRM</div>
            <div class="ps-3">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb mb-0 p-0">
                        <li class="breadcrumb-item">
                            <a asp-controller="Home" asp-action="Index"><i class="bx bx-home-alt"></i></a>
                        </li>
                        <li class="breadcrumb-item" aria-current="page">

                            <a asp-controller="Managers" asp-action="Index">Managers</a>
                        </li>
                        @if (Model.Id == 0)
                        {
                            <li class="breadcrumb-item active" aria-current="page">Create</li>
                        }
                        else
                        {
                            <li class="breadcrumb-item active" aria-current="page">Edit</li>
                        }

                    </ol>
                </nav>
            </div>
        </div>
        <div class="col mx-auto">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mx-auto">
                        <form asp-controller="Managers" asp-action="Edit" method="post">
                            <h2 class="text-center m-0">Manager</h2>
                            <div class="card-body">
                                @Html.HiddenFor(x => x.Id)
                                @Html.HiddenFor(x => x.Image)
                                @Html.HiddenFor(x => x.UserId)
                                <div class="row mb-3">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">First Name</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        <input type="text" class="form-control" asp-for="FirstName" />
                                        <span class="alert-danger" asp-validation-for="FirstName"></span>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Last Name</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        <input type="text" class="form-control" asp-for="LastName" />
                                        <span class="alert-danger" asp-validation-for="LastName"></span>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Email</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        <input type="text" class="form-control" asp-for="Email" />
                                        <span class="alert-danger" asp-validation-for="Email"></span>
                                    </div>
                                    @if (Model != null)
                                    {
                                        <div class="col-sm-9 text-secondary">
                                            <input type="hidden" class="form-control" asp-for="@Model.UserId" />
                                        </div>
                                    }
                                </div>
                                <div class="row mb-3">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Phone</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        <input type="text" placeholder="+375(XX)XXX-XX-XX" class="form-control" asp-for="Phone" />
                                        <span class="alert-danger" asp-validation-for="Phone"></span>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-3"></div>
                                    <div class="col-sm-9 text-secondary">
                                        <button type="submit" class="btn btn-outline-primary px-4">Save</button>
                                        <a type="button" class="btn btn-outline-danger px-4" asp-action="Index">Close</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ONX.CRM/Views/Managers/Index.cshtml
@{

    IEnumerable<ManagerViewModel> managersList = ViewBag.Managers;
}

@model ManagerViewModel

<div class="page-wrapper">
    <div class="page-content">
        <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
            <div class="breadcrumb-title pe-3">ONX.CRM</div>
            <div class="ps-3">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb mb-0 p-0">
                        <li class="breadcrumb-item">
                            <a asp-controller="Home" asp-action="Index"><i class="bx bx-home-alt"></i></a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">Managers</li>
                    </ol>
                </nav>
            </div>
        </div>
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row align-items-center">
                        <div class="float-lg-end">
                            <div class="row row-cols-lg-auto g-2">
                                <div class="col-12">
                                    <a asp-controller="Managers" asp-action="Edit" class="btn btn-outline-primary mb-3 mb-lg-0"><i class="bx bxs-plus-square"></i>Add new Manager</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <div>
                        <table class="table table-hover mb-0">
                            <thead class="table-light">
                                <tr>
                                    <th>ID</th>
                                    <th>Last Name</th>
                                    <th>First Name</th>
                                    <th>Email</th>
                                    <th>Phone</th>
                                    <th>View Details</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var manager in managersList)
                                {
                                    <tr>
                                        <td>@manager.Id</td>
                                        <td>@manager.LastName</td>
                                        <td>@manager.FirstName</td>
                                        <td>@manager.Email</td>
                                        <td>@manager.Phone</td>
                                        <td>
                                            <button type="button" class="btn btn-outline-primary btn-sm radius-30 px-4">View Details</button>
                                        </td>
                                        <td>
                                            <div class="d-flex order-actions">
                                                <div class="d-flex order-actions">
                                                    <div>
                                                        <a asp-controller="Managers" asp-action="Edit"
                                                           asp-route-id="@manager.Id"><i class='bx bxs-edit'></i></a>
                                                    </div>

                                                    <div class="ps-2">
                                                        <a asp-controller="Managers" asp-action="Delete"
                                                           asp-route-id="@manager.Id">
                                                            <i class='bx bxs-trash'></i>
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                }
                                <tr>
                                    <td>
                                        <div class="text-info">Total: @managersList.Count()</div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>