ONX.CRM/Controllers/UsersController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ONX.CRM.DAL.Models;
using ONX.CRM.Filters;
using ONX.CRM.ViewModel;

namespace ONX.CRM.Controllers
{
    [TypeFilter(typeof(LocalExceptionFilter))]
    public class UsersController : BaseController
    {
        private readonly UserManager<User> _userManager;

        public UsersController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            return View(_userManager.Users.ToList());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User
                {
                    LastName = model.LastName,
                    FirstName = model.FirstName,
                    Email = model.Email,
                    UserName = model.Email
                };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }
        public async Task<IActionResult> Edit(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel
            {
                Id = user.Id,
                LastName = user.LastName,
                FirstName = user.FirstName,
                Email = user.Email
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.FirstName = model.FirstName;
                    user.LastName = model.LastName;
                    user.Email = model.Email;
                    user.UserName = model.Email;

                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> ChangePassword(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ChangePasswordViewModel model = new ChangePasswordViewModel { Id = user.Id, Email = user.Email };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    IdentityResult result =
                        await _userManager.ChangePasswordAsync(user, model.OldPassword, model.NewPassword);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index", "Profile");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Пользователь не найден");
                }
            }
            return View(model);
        }
    }
}

ONX.CRM/Views/Users/ChangePassword.cshtml
@model ChangePasswordViewModel
@{
    ViewBag.Title = "Изменение пароля";
}

<div class="page-wrapper">
    <div class="page-content">
        <div class="row row-cols-1 row-cols-lg-2 row-cols-xl-3">
            <div class="col mx-auto">
                <div class="card">
                    <h2>Изменение пароля для пользователя @Model.Email</h2>
                    <form asp-action="ChangePassword" asp-controller="Users">
                        <div asp-validation-summary="All" class="text-danger"></div>
 
                        <input type="hidden" asp-for="Id" />
                        <input type="hidden" asp-for="Email" />
                        <div class="form-group">
                            <label asp-for="OldPassword" class="control-label">Старый пароль</label>
                            <input type="text" asp-for="OldPassword" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label asp-for="NewPassword" class="control-label">Новый пароль</label>
                            <input type="text" asp-for="NewPassword" class="form-control" />
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Сохранить" class="btn btn-default" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

ONX.CRM/Views/Users/Create.cshtml
@{
    ViewBag.Title = "Добавление пользователя";
}

@model CreateUserViewModel

<div class="page-wrapper">
    <div class="page-content">
        <div class="row row-cols-1 row-cols-lg-2 row-cols-xl-3">
            <div class="col mx-auto">
                <div class="card">
                    <form asp-action="Create" asp-controller="Users">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="FirstName" class="control-label">FirstName</label>
                            <input type="text" asp-for="FirstName" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label asp-for="LastName" class="control-label">LastName</label>
                            <input type="text" asp-for="LastName" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label asp-for="Email" class="control-label">Email</label>
                            <input type="text" asp-for="Email" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label asp-for="Password" class="control-label">Пароль</label>
                            <input type="password" asp-for="Password" class="form-control" />
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Добавить" class="btn btn-outline-secondary" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

ONX.CRM/Views/Users/Edit.cshtml
@{
    ViewBag.Title = "Редактирование пользователя";
}

@model EditUserViewModel

<div class="page-wrapper">
    <div class="page-content">
        <div class="row row-cols-1 row-cols-lg-2 row-cols-xl-3">
            <div class="col mx-auto">
                <div class="card">
                    <form asp-action="Edit" asp-controller="Users">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="form-group">
                            <input type="hidden" asp-for="Id" />
                        </div>
                        <div class="form-group">
                            <label asp-for="FirstName" class="control-label">FirstName</label>
                            <input type="text" asp-for="FirstName" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label asp-for="LastName" class="control-label">LastName</label>
                            <input type="text" asp-for="LastName" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label asp-for="Email" class="control-label">Email</label>
                            <input type="text" asp-for="Email" class="form-control" />
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Сохранить" class="btn btn-outline-secondary" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

ONX.CRM/Views/Users/Index.cshtml
@model IEnumerable<ONX.CRM.DAL.Models.User>
@{
    ViewBag.Title = "Список пользователей";
}

<div class="page-wrapper">
    <div class="page-content">
        <div class="row row-cols-1 row-cols-lg-2 row-cols-xl-3">
            <div class="col mx-auto">
                <div class="card">
                    <a class="btn btn-sm btn-primary" asp-controller="Users" asp-action="Create">Добавить пользователя</a>
                    <table class="table">
                        <tr><th>Email</th><th>Год</th><th></th></tr>
                        @foreach (var user in Model)
                        {
                            <tr>
                                <td>@user.LastName</td>
                                <td>@user.FirstName</td>
                                <td>@user.Email</td>
                                <td>
                                    <form asp-action="Delete" asp-route-id="@user.Id" method="post">
                                        <a class="btn btn-sm btn-primary" asp-action="Edit" asp-route-id="@user.Id">Изменить</a>
                                        <a class="btn btn-sm btn-primary" asp-controller="Profile" 
                                           asp-action="ChangePassword" asp-route-id="@user.Id">Сменить пароль</a>
                                        <button type="submit" class="btn btn-sm btn-danger">
                                            Удалить
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        }
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>